service: serverless-coffee

provider:
  name: aws
  stage: dev
  runtime: nodejs8.10
  region: us-east-1

package:
  exclude:
    - '.*/**'
  include:
    - dist.js

functions:
  api:
    handler: dist.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

