service: serverless-coffee

provider:
  name: aws
  stage: dev
  runtime: nodejs8.10
  region: us-east-1

functions:
  app:
    handler: dist.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

#  ping:
#    handler: handler.ping
#    events:
#      - http:
#          path: ping
#          method: get

